version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: equipo_db
      POSTGRES_USER: equipo_db_user
      POSTGRES_PASSWORD: equipo_db_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
